---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: config-apps
  path: ./apps/production
  postBuild:
    substitute:
      anon_image_registry_host: hub-registry.lab.okd.local
      apps_root: ./apps/production
      cluster_env: production
      secured_image_registry_host: registry.lab.okd.local
      vault_address: https://okd4-vault-1.lab.okd.local:8200
      vault_auth_kubernetes_mount_path: kubernetes-okd4
      vault_ca_cert: |
        -----BEGIN CERTIFICATE-----
        MIIEDjCCAvagAwIBAgIBBDANBgkqhkiG9w0BAQsFADBgMRwwGgYDVQQDExNwZlNl
        bnNlIExhYiBSb290IENBMQswCQYDVQQGEwJDQTEPMA0GA1UECBMGUXVlYmVjMQww
        CgYDVQQHEwNQQVQxFDASBgNVBAoTC3Bmc2Vuc2UubGFiMCAXDTIwMTExNTA2MDM1
        NloYDzIxMjAxMDIyMDYwMzU2WjBnMSMwIQYDVQQDExpwZlNlbnNlIE9LRCBJbnRl
        bWVkaWF0ZSBDQTELMAkGA1UEBhMCQ0ExDzANBgNVBAgTBlF1ZWJlYzEMMAoGA1UE
        BxMDUEFUMRQwEgYDVQQKEwtwZnNlbnNlLmxhYjCCASIwDQYJKoZIhvcNAQEBBQAD
        ggEPADCCAQoCggEBAOtZK11Y6ZcnBToFzxrQUC1iYAxRBp2KY5dQRa6L+bxmzL0B
        yCIwR3CfzFXBN3a1/Xf5z0yBachw6hAy2vd1qG+K1jdwwYTCaF6R3Eh+2qPxWjgU
        ugRfy5xu8IfYLVkF0UCPCSUoiEyammrzvFVHH0GCzCHCruO6xdHrMXfMnxZQSQDh
        yHQcWNlRIgac7hY0A0lWIi8iaLeJ61ohaO0KBttTaUqsDFUK+F+LYM65Gu2WfSCb
        arfkhVpd899gxOkD4+4venYhHrMGTZZCXQk695tEwtdu9OSPbq21h4L1RbIXrOiy
        c0vbqw90PCPBNsn20AQbxhiNHeIBtdTprjPfF/UCAwEAAaOByTCBxjAdBgNVHQ4E
        FgQUSV0PbLpu9x2u2ky8ZiNHs+m9WZwwgYkGA1UdIwSBgTB/gBRRSMwwHMIk3Xzh
        LmO/SEl3BPFHeKFkpGIwYDEcMBoGA1UEAxMTcGZTZW5zZSBMYWIgUm9vdCBDQTEL
        MAkGA1UEBhMCQ0ExDzANBgNVBAgTBlF1ZWJlYzEMMAoGA1UEBxMDUEFUMRQwEgYD
        VQQKEwtwZnNlbnNlLmxhYoIBADAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjAN
        BgkqhkiG9w0BAQsFAAOCAQEAwiEeYnLvpHWZQnN+siot6Y4tNnqlYaOdQnjsGnad
        M7n+DCfqHybLd97D4wCOOcRIwAjNOgB6ybZhOgW+ENnnQArNt7zZw2i/57eiWTM4
        NqSRAR6KsyMwYL0AZMR94WSeO0cgvZxdQhrKWgMLbLdNWV23iKjRqgrNGMiOS1Ke
        jyLzAlXAz4mplkksYc/JHR1ORcPyLCSsnKyvj331HCMzUQmkZf14QAi+gQpQP3if
        vNtZitRzSokaxQ6123g4K5laiDfyk58YwH5DJ5UR2mvYaleg/Aa0B5flesvqH77E
        cNVyd4MWFANlsBPwCUjGGIw8CAbyuvos8Z01L6rLMLALNw==
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIEBTCCAu2gAwIBAgIBADANBgkqhkiG9w0BAQsFADBgMRwwGgYDVQQDExNwZlNl
        bnNlIExhYiBSb290IENBMQswCQYDVQQGEwJDQTEPMA0GA1UECBMGUXVlYmVjMQww
        CgYDVQQHEwNQQVQxFDASBgNVBAoTC3Bmc2Vuc2UubGFiMB4XDTIwMDcwODE3Mzcw
        OVoXDTMwMDcwNjE3MzcwOVowYDEcMBoGA1UEAxMTcGZTZW5zZSBMYWIgUm9vdCBD
        QTELMAkGA1UEBhMCQ0ExDzANBgNVBAgTBlF1ZWJlYzEMMAoGA1UEBxMDUEFUMRQw
        EgYDVQQKEwtwZnNlbnNlLmxhYjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
        ggEBAOVwDa+ygzKSGX0htZ897QJzF4BdMTL4/H1cCbVbGUxdgWOfm4Bm8jSaFiCO
        0Fx4HzmJ5ObqUQh6Tb62IrMBi4IbJZI8/3JVREZx4f4K+T1E2A8VdtP7Kvlvtodp
        Hy139fSK0Eut7uLMEMC9HaowRXTvuB6V2tZQGDL7vse1iKMSO/BfqQ44pB4BpJNH
        O53Rv9uZIE7b1T9lqNU0O6bEn1hdd96CCFsuAxnFbd4ITrmgXE2jsf2UX/Bykuph
        hQvgOcNEU0rB4LMVAVXfcb+BicHnMparlB0USDWXZNyDscJsP3b0pO75OlY6a3LC
        YSnKhsnIrEXq1365Oc9j9TdJziUCAwEAAaOByTCBxjAdBgNVHQ4EFgQUUUjMMBzC
        JN184S5jv0hJdwTxR3gwgYkGA1UdIwSBgTB/gBRRSMwwHMIk3XzhLmO/SEl3BPFH
        eKFkpGIwYDEcMBoGA1UEAxMTcGZTZW5zZSBMYWIgUm9vdCBDQTELMAkGA1UEBhMC
        Q0ExDzANBgNVBAgTBlF1ZWJlYzEMMAoGA1UEBxMDUEFUMRQwEgYDVQQKEwtwZnNl
        bnNlLmxhYoIBADAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG9w0B
        AQsFAAOCAQEAYienYZE3reVPZ8n+pwvFmJl1JYeo9dzUeEpXU/mZZBdyHsYusQeQ
        /mzZM9au6kjCYS6qr6sCNGx/lSHann7lP6KMCDyL86+KEoLOWOGB7CwOK7HSWxO+
        hvmOsigK+UoNfmNln8eECU5KfPCRQxkWITXVn9OOVCvDl6zbSIwlM2FbseXAd+W2
        1ol3KtVrk2xRVa4g6gQnjRKaTEFl5QMvC9NEouhmtZRf/bfW0zpArfombFT9PpeT
        /moarJnO/ARGcpXkl7YZgmgdZ+mfIkupiinwWjLj/9DwYl8wMoLN0gmPDx6b613F
        0FBOAVL6iXotIYqVRwbUg5OjjqYibNOLTg==
        -----END CERTIFICATE-----
      vault_ca_cert_base64: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVEakNDQXZhZ0F3SUJBZ0lCQkRBTkJna3Foa2lHOXcwQkFRc0ZBREJnTVJ3d0dnWURWUVFERXhOd1psTmwKYm5ObElFeGhZaUJTYjI5MElFTkJNUXN3Q1FZRFZRUUdFd0pEUVRFUE1BMEdBMVVFQ0JNR1VYVmxZbVZqTVF3dwpDZ1lEVlFRSEV3TlFRVlF4RkRBU0JnTlZCQW9UQzNCbWMyVnVjMlV1YkdGaU1DQVhEVEl3TVRFeE5UQTJNRE0xCk5sb1lEekl4TWpBeE1ESXlNRFl3TXpVMldqQm5NU013SVFZRFZRUURFeHB3WmxObGJuTmxJRTlMUkNCSmJuUmwKYldWa2FXRjBaU0JEUVRFTE1Ba0dBMVVFQmhNQ1EwRXhEekFOQmdOVkJBZ1RCbEYxWldKbFl6RU1NQW9HQTFVRQpCeE1EVUVGVU1SUXdFZ1lEVlFRS0V3dHdabk5sYm5ObExteGhZakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBT3RaSzExWTZaY25CVG9GenhyUVVDMWlZQXhSQnAyS1k1ZFFSYTZMK2J4bXpMMEIKeUNJd1IzQ2Z6RlhCTjNhMS9YZjV6MHlCYWNodzZoQXkydmQxcUcrSzFqZHd3WVRDYUY2UjNFaCsycVB4V2pnVQp1Z1JmeTV4dThJZllMVmtGMFVDUENTVW9pRXlhbW1yenZGVkhIMEdDekNIQ3J1TzZ4ZEhyTVhmTW54WlFTUURoCnlIUWNXTmxSSWdhYzdoWTBBMGxXSWk4aWFMZUo2MW9oYU8wS0J0dFRhVXFzREZVSytGK0xZTTY1R3UyV2ZTQ2IKYXJma2hWcGQ4OTlneE9rRDQrNHZlblloSHJNR1RaWkNYUWs2OTV0RXd0ZHU5T1NQYnEyMWg0TDFSYklYck9peQpjMHZicXc5MFBDUEJOc24yMEFRYnhoaU5IZUlCdGRUcHJqUGZGL1VDQXdFQUFhT0J5VENCeGpBZEJnTlZIUTRFCkZnUVVTVjBQYkxwdTl4MnUya3k4WmlOSHMrbTlXWnd3Z1lrR0ExVWRJd1NCZ1RCL2dCUlJTTXd3SE1JazNYemgKTG1PL1NFbDNCUEZIZUtGa3BHSXdZREVjTUJvR0ExVUVBeE1UY0daVFpXNXpaU0JNWVdJZ1VtOXZkQ0JEUVRFTApNQWtHQTFVRUJoTUNRMEV4RHpBTkJnTlZCQWdUQmxGMVpXSmxZekVNTUFvR0ExVUVCeE1EVUVGVU1SUXdFZ1lEClZRUUtFd3R3Wm5ObGJuTmxMbXhoWW9JQkFEQU1CZ05WSFJNRUJUQURBUUgvTUFzR0ExVWREd1FFQXdJQkJqQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBd2lFZVluTHZwSFdaUW5OK3Npb3Q2WTR0Tm5xbFlhT2RRbmpzR25hZApNN24rRENmcUh5YkxkOTdENHdDT09jUkl3QWpOT2dCNnliWmhPZ1crRU5ublFBck50N3padzJpLzU3ZWlXVE00Ck5xU1JBUjZLc3lNd1lMMEFaTVI5NFdTZU8wY2d2WnhkUWhyS1dnTUxiTGROV1YyM2lLalJxZ3JOR01pT1MxS2UKanlMekFsWEF6NG1wbGtrc1ljL0pIUjFPUmNQeUxDU3NuS3l2ajMzMUhDTXpVUW1rWmYxNFFBaStnUXBRUDNpZgp2TnRaaXRSelNva2F4UTYxMjNnNEs1bGFpRGZ5azU4WXdINURKNVVSMm12WWFsZWcvQWEwQjVmbGVzdnFINzdFCmNOVnlkNE1XRkFObHNCUHdDVWpHR0l3OENBYnl1dm9zOFowMUw2ckxNTEFMTnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFQlRDQ0F1MmdBd0lCQWdJQkFEQU5CZ2txaGtpRzl3MEJBUXNGQURCZ01Sd3dHZ1lEVlFRREV4TndabE5sCmJuTmxJRXhoWWlCU2IyOTBJRU5CTVFzd0NRWURWUVFHRXdKRFFURVBNQTBHQTFVRUNCTUdVWFZsWW1Wak1Rd3cKQ2dZRFZRUUhFd05RUVZReEZEQVNCZ05WQkFvVEMzQm1jMlZ1YzJVdWJHRmlNQjRYRFRJd01EY3dPREUzTXpjdwpPVm9YRFRNd01EY3dOakUzTXpjd09Wb3dZREVjTUJvR0ExVUVBeE1UY0daVFpXNXpaU0JNWVdJZ1VtOXZkQ0JEClFURUxNQWtHQTFVRUJoTUNRMEV4RHpBTkJnTlZCQWdUQmxGMVpXSmxZekVNTUFvR0ExVUVCeE1EVUVGVU1SUXcKRWdZRFZRUUtFd3R3Wm5ObGJuTmxMbXhoWWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQU9Wd0RhK3lnektTR1gwaHRaODk3UUp6RjRCZE1UTDQvSDFjQ2JWYkdVeGRnV09mbTRCbThqU2FGaUNPCjBGeDRIem1KNU9icVVRaDZUYjYySXJNQmk0SWJKWkk4LzNKVlJFWng0ZjRLK1QxRTJBOFZkdFA3S3ZsdnRvZHAKSHkxMzlmU0swRXV0N3VMTUVNQzlIYW93UlhUdnVCNlYydFpRR0RMN3ZzZTFpS01TTy9CZnFRNDRwQjRCcEpOSApPNTNSdjl1WklFN2IxVDlscU5VME82YkVuMWhkZDk2Q0NGc3VBeG5GYmQ0SVRybWdYRTJqc2YyVVgvQnlrdXBoCmhRdmdPY05FVTByQjRMTVZBVlhmY2IrQmljSG5NcGFybEIwVVNEV1haTnlEc2NKc1AzYjBwTzc1T2xZNmEzTEMKWVNuS2hzbklyRVhxMTM2NU9jOWo5VGRKemlVQ0F3RUFBYU9CeVRDQnhqQWRCZ05WSFE0RUZnUVVVVWpNTUJ6QwpKTjE4NFM1anYwaEpkd1R4UjNnd2dZa0dBMVVkSXdTQmdUQi9nQlJSU013d0hNSWszWHpoTG1PL1NFbDNCUEZICmVLRmtwR0l3WURFY01Cb0dBMVVFQXhNVGNHWlRaVzV6WlNCTVlXSWdVbTl2ZENCRFFURUxNQWtHQTFVRUJoTUMKUTBFeER6QU5CZ05WQkFnVEJsRjFaV0psWXpFTU1Bb0dBMVVFQnhNRFVFRlVNUlF3RWdZRFZRUUtFd3R3Wm5ObApibk5sTG14aFlvSUJBREFNQmdOVkhSTUVCVEFEQVFIL01Bc0dBMVVkRHdRRUF3SUJCakFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQVlpZW5ZWkUzcmVWUFo4bitwd3ZGbUpsMUpZZW85ZHpVZUVwWFUvbVpaQmR5SHNZdXNRZVEKL216Wk05YXU2a2pDWVM2cXI2c0NOR3gvbFNIYW5uN2xQNktNQ0R5TDg2K0tFb0xPV09HQjdDd09LN0hTV3hPKwpodm1Pc2lnSytVb05mbU5sbjhlRUNVNUtmUENSUXhrV0lUWFZuOU9PVkN2RGw2emJTSXdsTTJGYnNlWEFkK1cyCjFvbDNLdFZyazJ4UlZhNGc2Z1FualJLYVRFRmw1UU12QzlORW91aG10WlJmL2JmVzB6cEFyZm9tYkZUOVBwZVQKL21vYXJKbk8vQVJHY3BYa2w3WVpnbWdkWittZklrdXBpaW53V2pMai85RHdZbDh3TW9MTjBnbVBEeDZiNjEzRgowRkJPQVZMNmlYb3RJWXFWUndiVWc1T2pqcVlpYk5PTFRnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      vault_kv_engine_secret_mount_path: kv/okd4
      vault_pki_mount_path: pki_int_lab_okd_local
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: config-apps
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: k8s
  secretRef:
    name: config-apps
  url: https://gitlab.lab.okd.local/gitops/flux-infra.git